//
//  Data.swift
//  ChooseTemplate
//
//  Created by Derek Fitzer on 3/28/23.
//

import Foundation



class Page{
    var pageNumber: Int
    var dataEnteredBy: String  // your name
    var pageText: String // make sure to remove extra spaces after pasting
    var pageImage1: String
    var choices: Int // 1 to contine or end, 2 or 3 if appropriate
    var pageChoiceOneText: String // remove if, capitalize the Y and add a period.
    var pageChoiceOneNav: Int
    var pageChoiceTwoText: String
    var pageChoiceTwoNav: Int
    var pageChoiceThreeText: String
    var pageChoiceThreeNav: Int
    init(pageNumber: Int, dataEnteredBy: String, pageText: String, pageImage1: String, choices: Int, pageChoiceOneText: String, pageChoiceOneNav: Int, pageChoiceTwoText: String, pageChoiceTwoNav: Int, pageChoiceThreeText: String, pageChoiceThreeNav: Int) {
        self.pageNumber = pageNumber
        self.dataEnteredBy = dataEnteredBy
        self.pageText = pageText
        self.pageImage1 = pageImage1
        self.choices = choices
        self.pageChoiceOneText = pageChoiceOneText
        self.pageChoiceOneNav = pageChoiceOneNav
        self.pageChoiceTwoText = pageChoiceTwoText
        self.pageChoiceTwoNav = pageChoiceTwoNav
        self.pageChoiceThreeText = pageChoiceThreeText
        self.pageChoiceThreeNav = pageChoiceThreeNav
    }
}

// Checked by: Someone....
let p1 = Page(pageNumber: 1, dataEnteredBy: "Fitzer", pageText: "JOURNEY UNDER THE SEA CHOOSE YOUR OWN ADVENTURE • 2 From time to time as you read along, you will be asked to make a choice. Your choice may lead to success or disaster! The adventures you take are a result of your choice. You are responsible because you choose! After you make your choice follow the instructions to see what happens to you next. Remember—you cannot go back! Think carefully before you make a move! One mistake can be your last ... or it may lead you to fame and fortune!", pageImage1: "",choices: 1, pageChoiceOneText: "Continue", pageChoiceOneNav: 2, pageChoiceTwoText: "", pageChoiceTwoNav: 0, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

// Checked by: ....
let p2 = Page(pageNumber: 2, dataEnteredBy: "Fitzer", pageText: "You are an underwater explorer. You are leaving to explore the deepest oceans. You must find the lost city of Atlantis. This is your most challenging assignment. It is morning and the sun pushes up on the horizon. The sea is calm. You climb into the narrow pilot's compartment of the underwater vessel Seeker with your special gear. The crew of the research vessel Maray screws down the hatch clamps. Now begins the plunge into the depths of the ocean. The Seeker crew begins lowering by a strong, but thin cable. Within minutes, you are so deep in the ocean that little light filters down to you. The silence is eerie as the Seeker slips deeper and deeper. You peer out the thick glass porthole and see fish drifting past, sometimes stopping to look at you—an intruder from another world.", pageImage1: "p2",  choices: 1, pageChoiceOneText: "Continue", pageChoiceOneNav: 3, pageChoiceTwoText: "", pageChoiceTwoNav: 0, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

let p3 = Page(pageNumber: 3, dataEnteredBy: "Fitzer", pageText: "Now the cable attaching you to Maray is ex- tended almost to its limit. You have come to rest on a ledge near the canyon in the ocean floor that supposedly leads to the lost city of Atlantis. You have a special sea suit that will protect you from the intense pressure of the deep if you choose to walk about on the sea bottom. You can cut loose from the cable if you wish because the Seeker is self-propelled. You are now in another world.", pageImage1: "p3", choices: 2, pageChoiceOneText: "you decide to explore the ledge where the Seeker has come to rest", pageChoiceOneNav: 6, pageChoiceTwoText: "you decide to cut loose from the Maray and dive with the Seeker into the canyon in the ocean floor", pageChoiceTwoNav: 5, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

let p4 = Page(pageNumber: 4, dataEnteredBy: "Fitzer", pageText: "", pageImage1: "p4", choices: 1, pageChoiceOneText: "Continue", pageChoiceOneNav: 5, pageChoiceTwoText: "", pageChoiceTwoNav: 0, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

let p5 = Page(pageNumber: 5, dataEnteredBy: "Fitzer", pageText: "You radio a status report to the Moray and tell them that you are going to cast off from the line and descend under your own power. Your plan is approved and you cast off your line. Now you are on your own. The Seeker slips noiselessly into the undersea canyon. As you drop into the canyon, you turn on the Seeker's powerful searchlight. Straight ahead is a dark wall covered with a strange type of barnacle growth. To the left (port) side you see what ap- pears to be a grotto. The entrance is perfectly round, as if it had been cut by human hands. Lantern fish give off a pale, greenish light. To the right (starboard) side of the Seeker you see bub- bles rising steadily from the floor of the canyon.", pageImage1: "", choices: 2, pageChoiceOneText: "you decide to investigate the bubbles", pageChoiceOneNav: 8, pageChoiceTwoText: "you decide to investigate the grotto with the round entrance", pageChoiceTwoNav: 9, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

let p6 = Page(pageNumber: 6, dataEnteredBy: "Fitzer", pageText: "Your sea suit will protect you from the intense pressures of the deep. It is a tight fit and takes you some time to put it on. Finally you slip from the airlock of the Seeker and stand on the ocean floor. It is a strange and marvelous world where your every move is slowed down. You begin to explore with your special hand-held searchlight. You examine the ledge by the canyon. Suddenly, a school of bright yellow angel fish dart by, almost brushing you. What made them move so fast? Are they being chased? Then you see it. The Seeker is in the grips of a huge sea monster. It is similar to a squid, but it is enormous. The Seeker is just a toy in its long, powerful tentacles. You seek shelter behind a rock formation. You know the spear gun you carry will be useless against this monster. It looks as though it will destroy the Seeker. Fish of all sizes huddle with you in an attempt to escape the monster.", pageImage1: "", choices: 2, pageChoiceOneText: "You stay hidden close to the Seeker.", pageChoiceOneNav: 10, pageChoiceTwoText: "You try to escape in the hope that rescuers will see you.", pageChoiceTwoNav: 12, pageChoiceThreeText: "", pageChoiceThreeNav: 0)
//Data Entry        Start Page    End Page    Quality Review
//Dylan  Beasley    7     14    Shamsa Mohamed

var p7 = Page(pageNumber: 7, dataEnteredBy: "Beasley", pageText: "Carefully, you maneuver the Seeker between the walls of the canyon. On the floor of the canyon, you discover a large round hole out of which flow the large bubbles. The Seeker is equipped with scientific equipment to analyze the bubbles. It also has sonar equipment that can measure the depth of any hole.", pageImage1: "p7", choices: 2, pageChoiceOneText: "If you decide to analyze the bubbles.", pageChoiceOneNav: 11, pageChoiceTwoText: "If you decide to take sonar readings.", pageChoiceTwoNav: 15, pageChoiceThreeText: "", pageChoiceThreeNav: 0)
var p8 = Page(pageNumber: 8, dataEnteredBy: "Beasley", pageText: "You pilot the Seeker through the rounded entrance to the grotto. Once inside, your searchlight picks up what appear to be docks and piers along the grotto walls. The Seeker's searchlight is not very powerful. However, you do have a special laser light which would light up the grotto like daylight. Unfortunately, the laser light can only be used twice for very short periods before it must be recharged aboard the Maray, now more than 2,000 feet above you on the surface.", pageImage1: "page 14", choices: 2, pageChoiceOneText: "If you decide to use the laser light,", pageChoiceOneNav: 16, pageChoiceTwoText: "If you decide to cruise further into the grotto,", pageChoiceTwoNav: 14, pageChoiceThreeText: "", pageChoiceThreeNav: 0)
var p9 = Page(pageNumber: 10, dataEnteredBy: "Beasley", pageText: "The giant squid tosses and turnsthe Seeker, but finally the creature growstired of its new game and jets off with an enormous squirt of water. You now are free to leave your hiding place and examine the Seeker for damage. To your dismay, the airlock entrance has been jammed shut. You are locked out of the Seeker. The crew of the Maray, however, suspected trouble when you did not respond to a routine radio check and they are now lowering an escape platform to you. Once on the platform, you radio them to start the slow pull to the surface. To avoid the bends—rapid expansion of nitrogen bubbles in your blood—they will have to bring you up very slowly. Just as the platform begins to move, the giant squid suddenly returns as if from nowhere. It is headed directly at you.", pageImage1: "", choices: 2, pageChoiceOneText: "If you decide to fight the squid with yourspear gun, hoping to scare it off.", pageChoiceOneNav: 178, pageChoiceTwoText: "If you decide to signal Maray to pull you up at top speed, knowing you will get the bends.", pageChoiceTwoNav: 18, pageChoiceThreeText: "", pageChoiceThreeNav: 0)
var p10 = Page(pageNumber: 11, dataEnteredBy: "Beasley", pageText: "You squeeze into your sea suit and, outside the Seeker, you use special equipment to analyze the bubbles. As you work, you clumsily knock against the valve that dumpsthe compressed air necessary to make the Seeker rise to the surface. There is nothing to be done about it; so you continue to analyze the bubbles. They contain a high percentage of oxygen and no poisonous gases. Perhaps they are coming from some area below the sea where human-type beings can live and breathe. Perhaps they are coming from Atlantis. You wonder whether you should try the Seeker's drilling arm to enlarge the source of the bubbles so you can explore it with the Seeker. But you are also very worried about the Seeker's loss of rising capability. You might also be able to trap the bubbles and use them to raise the Seeker.", pageImage1: "", choices: 2, pageChoiceOneText: "If you try to collect the bubbles coming from the hole to fill the tanks of the Seeker,", pageChoiceOneNav: 24, pageChoiceTwoText: "If you decide to drill", pageChoiceTwoNav: 22, pageChoiceThreeText: "0", pageChoiceThreeNav: 0)
var p11 = Page(pageNumber: 12, dataEnteredBy: "Beasley", pageText: "Moving cautiously, you climb up the sides of the canyon hoping to reach the ocean floor. You leave the Seekerin the grips of the giantsquid. Your plan is to signal for help with a dye marker that will float to the surface and make a bright yellow patch in the water. The crewmen above have been instructed to watch for such emergency signals. They will send help. Once you reach the ledge above the canyon and feel slightiy safer, you see the most feared of all sea creatures— a huge shark. It begins to circle towards you and you know that you are its target. You wonder whether you should fire your emergency propulsion charge that will send you rapidly to the surface. The shark is fast; he might catch you anyway. You also know that you will get the bends from the rapid rise to the surface.", pageImage1: "p19", choices: 2, pageChoiceOneText: "If you decide to fire the special propulsion charge to get to the surface,", pageChoiceOneNav: 21, pageChoiceTwoText: "If you decide to wait quietly hoping that the shark will go away,", pageChoiceTwoNav: 19, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

var p12 = Page(pageNumber: 13, dataEnteredBy: "Beasley", pageText: "", pageImage1: "p13", choices: 1, pageChoiceOneText: "Continue", pageChoiceOneNav: 13, pageChoiceTwoText: "", pageChoiceTwoNav: 0, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

var p13 = Page(pageNumber: 14, dataEnteredBy: "Beasley", pageText: "You cruise silently into the grotto. Its roof seems to slope upward and you follow the slope. The depth finder shows that you are rising quite rapidly. Perhaps you will reach the surface and open air. Then the roof of the grotto stops sloping upward. Before you is a perfectly round metallic hatch made of a metal that you have never seen before. With the mechanical arm of the Seeker you try to open the hatch. It will not open. You begin to send radio signals at the door hoping to make contact on the other side.", pageImage1: "p14", choices: 2, pageChoiceOneText: "If you decide to blow the hatch open with an explosive charge,", pageChoiceOneNav: 26, pageChoiceTwoText: "If you decide to continue transmitting radio communications through the hatch,", pageChoiceTwoNav: 28, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

var p14 = Page(pageNumber: 15, dataEnteredBy: "Beasley", pageText: "You maneuver the Seeker next to the hole and begin to take sonar readings to determine the depth of the hole. To your amazement, the sonar readings indicate that the hole is extraordinarily deep it might reach the center of the earth! What lies down there? Where are the bubbles coming from? Is Atlantis beneath you? Then you notice a disturbing reading on your instruments; a mild earthquake has occurred. The Seeker is not damaged, but the earthquake could set up a tsunami wave on the surface causing the Moray to leave forsafer areas. It might be dangerous not to get back to the surface and leave with the Moray. On the other hand, you are perhaps on the verge of one of the world's greatest discoveries.", pageImage1: "", choices: 2, pageChoiceOneText: "If you decide to descend into the hole", pageChoiceOneNav: 23, pageChoiceTwoText: "If you decide to return to the surface", pageChoiceTwoNav: 27, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

//Cyrus Butcher     15    22    Nathaniel Peoples
var p15 = Page(pageNumber: 15, dataEnteredBy: "Fitzer", pageText: "You maneuver the Seeker next to the hole and begin to take sonar readings to determine the depth of the hole. To your amazement, the sonar readings indicate that the hole is extraordinarily deep— it might reach the center of the earth! What lies down there? Where are the bubbles coming from? Is Atlantis beneath you? Then you notice a disturbing reading on your instruments; a mild earthquake has occurred. The Seeker is not damaged, but the earthquake could set up a tsunami wave on the surface causing the Moray to leave for safer areas. It might be danger- ous not to get back to the surface and leave with the Moray. On the other hand, you are perhaps on the verge of one of the world's greatest dis- coveries.", pageImage1: "", choices: 2, pageChoiceOneText: "You decide to descend into the hole.", pageChoiceOneNav: 23, pageChoiceTwoText: "You decide to return to the surface", pageChoiceTwoNav: 27, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

var p16 = Page(pageNumber: 16, dataEnteredBy: "Fitzer", pageText: "The beam from the laser light illuminates the entire grotto. Far back on the floor of the grotto is a submarine! Cautiously, you maneuver the Seeker closer. You identify it as the submarine that myste- riously disappeared in the Bermuda Triangle al- most a year before. The Bermuda Triangle is more than 2000 miles away.The submarine is apparently not damaged, but it is covered with a slimy algae. Beautiful fish swim around it as though it is their own special prize. Then you notice that the main hatch is free of algae!", pageImage1: "", choices: 2, pageChoiceOneText: "try to enter the submarine", pageChoiceOneNav: 29, pageChoiceTwoText: "Cruise on through the grotto.", pageChoiceTwoNav: 31, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

var p17 = Page(pageNumber: 17, dataEnteredBy: "Fitzer", pageText: "With a rush of water, the giant squid attacks you. Two 20 foot tentacles with their pulsing suction cups reach out trying to ensnare you. You dive off the platform and rapidly fire two of your spears. They strike the squid close to its two monstrous eyes. But the squid keeps on coming. One of the tentacles wraps around your diving helmet and ruptures the seal to your suit. You fire your last spear hoping to hit the monster in a vulnerable spot. Water is beginning to trickle into your suit. You signal the Maray to haul you up fast— 'Emergency Hoist.' You must have hit the squid. It floats away writhing and thrashing. You think you're about to black out.You wake up on the deck of the Moray and are quickly rushed to the decompression chambers to ward off the effect of the bends. In a few days you are better and start to worry about diving into the abyss again.", pageImage1: "", choices: 2, pageChoiceOneText: "You decide to quit the expedition now", pageChoiceOneNav: 32, pageChoiceTwoText: "You decide to go back down to the deep.", pageChoiceTwoNav: 33, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

var p18 = Page(pageNumber: 18, dataEnteredBy: "Fitzer", pageText: "As they begin the rapid hauling, you lose your ability to function in the deep. You start to get dizzy and your arms and legs feel weak. You lose your hold on the platform and drift in the water exhausted. Then you see a dolphin heading to- ward you. You know that these marvelous mammals sometimes help people in trouble. Will it help you?", pageImage1: "", choices: 2, pageChoiceOneText: "You try to get help from the dolphin.", pageChoiceOneNav: 34, pageChoiceTwoText: "you decide to carry on alone swimming to the surface", pageChoiceTwoNav: 37, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

var p19 = Page(pageNumber: 19, dataEnteredBy: "Fitzer", pageText: " You wait for the shark to go away. But then you notice other sharks coming to join in the hunt. They circle you, coming closer and faster each time. It is too late. There is no escape!", pageImage1: "p", choices: 1, pageChoiceOneText: "The End", pageChoiceOneNav: 0, pageChoiceTwoText: "", pageChoiceTwoNav: 0, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

var p20 = Page(pageNumber: 20, dataEnteredBy: "Fitzer", pageText: "", pageImage1: "p20", choices: 1, pageChoiceOneText: "Continue", pageChoiceOneNav: 21, pageChoiceTwoText: "", pageChoiceTwoNav: 0, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

var p21 = Page(pageNumber: 21, dataEnteredBy: "Fitzer", pageText: " You fire the special propulsion charge and zoom upward through the water, frightening schools of fish as you go. You become dizzy and lose track of where you are. The world seems upside down. The shark is nowhere around, you hope. Then you break through to the surface floating about a half mile from the Maray.The lookouts spot you in the water and quickly rescue you. Unfortunately, the rapid ascent has given you a bad case of the bends. It takes a long time to decompress. And when you are finally all right, the ship's doctor informs you that your underwater days are over. Someone else will have to find Atlantis.", pageImage1: "", choices: 1, pageChoiceOneText: "The End", pageChoiceOneNav: 0, pageChoiceTwoText: "", pageChoiceTwoNav: 0, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

var p22 = Page(pageNumber: 22, dataEnteredBy: "Fitzer", pageText: "As you begin to drill, the stream of bubbles increases. The stream of bubbles is strong enough now to ruffle the surface of the sea. You could try to surface now and locate the exact position of the bubble area. Then you could make plans with the scientists aboard the Moray about what to do next. But also, you could simply explore the hole with the Seeker to determine the source of the bubbles now! There is great risk in entering the hole, but it could lead to the source of the bubbles and maybe to Atlantis.", pageImage1: "", choices: 2, pageChoiceOneText: "You explore.", pageChoiceOneNav: 38, pageChoiceTwoText: "You try to surface", pageChoiceTwoNav: 35, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

//Jacob Davis       23    30    Max Stephenson
var p23 = Page(pageNumber: 23, dataEnteredBy: "Jacob", pageText: "Now is the time for decision. You check all thecontrols of the Seeker, grit your teeth, and push the control column into the deep dive position. Down, down you go where no person has ever ventured. The Seeker is built for deep, deep dives,but you are descending rapidly mile after mile into the deep. The pressure is intense, the darkness is complete, and the depth guage indicates an incredible 15 miles. You quickly reverse the control column. Warning lights flare up on your control panel; they show that gravitational forces are now stronger than the Seeker's propulsion motors. You have passed the point of no return and your journey downward will continue in utter darkness untilthe water pressure is too great for the Seeker. Thisis the final voyage.", pageImage1: "", choices: 1, pageChoiceOneText: "The End", pageChoiceOneNav: 0, pageChoiceTwoText: "", pageChoiceTwoNav: 0, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

var p24 = Page(pageNumber: 24, dataEnteredBy: "Jacob", pageText: "You are able to capture the bubbling gases and fill the tanks of the Seeker, enough to allow it to rise. Slowly, the Seeker rises out of the canyon, scattering schools of brightly colored fish, and brushing past underwater plants that wave like palm trees in a wind. Just as you reach the ledge at the top of the canyon, you see what appears to be an old road! Rocks along its side seem to be guard rails. Could this be a path that leads to the lost city of Atlantis? You anchor the Seeker and prepare to investigate more closely.", pageImage1: "", choices: 1, pageChoiceOneText: "Turn to page 6", pageChoiceOneNav: 6, pageChoiceTwoText: "", pageChoiceTwoNav: 0, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

var p25 = Page(pageNumber: 25, dataEnteredBy: "Jacob", pageText: "", pageImage1: "p25", choices: 1, pageChoiceOneText: "Continue", pageChoiceOneNav: 26, pageChoiceTwoText: "", pageChoiceTwoNav: 0, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

var p26 = Page(pageNumber: 26, dataEnteredBy: "Jacob", pageText: "The only way to get beyond the door isto blast it away, or so you believe. The Seeker's laser cannon is powerful and you position the Seeker to fire. Pushing the fire button, you send a powerful beam at the hatch. Nothing happens. Then you advance the cannon control to full emergency force. Again you push the button and the beam dissolves the hatch instantly. A flood ofsea water rushesinto the giant hole, carrying you with it into an air-filled cavern beyond. The water fills the cavern with speed and explosive force. You see several people scurrying towards escape hatches. IT IS TOO LATE! You did the wrong thing.", pageImage1: "p26", choices: 1, pageChoiceOneText: "The End", pageChoiceOneNav: 0, pageChoiceTwoText: "", pageChoiceTwoNav: 0, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

var p27 = Page(pageNumber: 27, dataEnteredBy: "Jacob", pageText: "Deciding to return to the surface, you direct the  Seeker cautiously back along the side of the can- yon in the ocean floor. Without warning, the  Seekeris gripped in a powerful current thatsweeps it toward a grotto. Once in the grotto, the current carries you to what appears to be a large metal  door. It swings open and the Seeker is swept in- side. The door closes, the water in the grotto drains  away, and you step out into a chamber that you decide must be made by human hands. A door opens in the wall, two people dressed in simple clothes come towards you. One of them  says, 'Welcome to Atlantis. We have been expecting you.'  What a discovery! You have found the lost con- tinent and its civilization. The two people tell you  that although citizens of Atlantis occasionally jour- ney to the upper world, anyone who happens  upon Atlantis is never permitted to leave. The Atlanteans are not cruel but fear discovery of their world. They want you to follow them and you agree. But you have another thought. Perhaps you could blast your way out of the chamber with the Seeker's laser cannon.", pageImage1: "", choices: 2, pageChoiceOneText: "You decide to follow the people and join the Atlantean society", pageChoiceOneNav: 39, pageChoiceTwoText: "You decide to make a dash for the Seeker and try to blast through the closed door with the laser cannon", pageChoiceTwoNav: 40, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

var p28 = Page(pageNumber: 28, dataEnteredBy: "Jacob", pageText: "The radio transmissions seem to be failing, and you grow tired of sending signals through the closed door. You are just about to give up when the doorsuddenly swings open revealing behind it a cavern with another door. You enter the cavern cautiously and receive a radio signal in English. It tells you that you are welcome here, but that once you enter this place, you may never return to the world above. It is up to you to decide.", pageImage1: "", choices: 2, pageChoiceOneText: "You decide to go on and investigate what might be Atlantis,", pageChoiceOneNav: 41, pageChoiceTwoText: "You decide to retreat", pageChoiceTwoNav: 42, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

var p29 = Page(pageNumber: 29, dataEnteredBy: "Jacob", pageText: "The submarine is indeed mysterious. You now have on your sea suit and you open the hatch on  the conning tower and enter the sub. It is amazingly clean and in order. There are no signs of life,  but there are also no signs ofstruggle or trouble. In the control room, you see a piece of mystifying equipment that just doesn't belong on this sub. A voice begins telling you that, thousands of years ago, the leaders of Atlantis realized that their  continent was slipping into the sea. They discov- ered a large underground cavern and built new  forms of living quarters for their people. Later when Atlantis was deep beneath the ocean, some  of their scientists discovered and perfected an operation enabling them to breathe under water.  The voice, which sounds friendly, also tells you that there are two groups in Atlantis. One group is good and the other is evil. The voice invites you to enter the world of Atlantis and gives directions and  instructions to a secret passageway to the underwater city.  As you follow directions, you spy an unbelievable underwater craft with several people in it. It  must be an Atlantean ship, but are the people  good or evil? Do they know of the secret passage- way?", pageImage1: "", choices: 2, pageChoiceOneText: "You hurry in, trying to reach the secret passageway without being seen", pageChoiceOneNav: 43, pageChoiceTwoText: "You rush back to the Seeker trying to escape danger", pageChoiceTwoNav: 44, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

var p30 = Page(pageNumber: 30, dataEnteredBy: "Jacob", pageText: "", pageImage1: "p30", choices: 1, pageChoiceOneText: "Continue", pageChoiceOneNav: 31, pageChoiceTwoText: "", pageChoiceTwoNav: 0, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

//Gabrel Delgado    31    38    Johnny Slabaugh

let p31 = Page(pageNumber: 31, dataEnteredBy: "Delgado", pageText: "You cruise through the grotto past the wreck ofthe submarine and then you spot another shipwreck. And then another. They, too, are coveredwith algae, but they appear undamaged. Maybe people from Atlantis capture ships in the Bermuda Triangle and bring them here. Then you seeanother ship, but this one is a three-masted schooner of the type used in the early 1800s. Its rigging isfestooned with algae, and fish swim lazily around its mast. Your curiosity captures you and you put on your sea suit. Leaving the Seeker, you move towards the old sailing ship. Suddenly a thirteen-foot long deadly poisonous sea snake strikes from behind the forward cabin and bites you in the soft flesh between the fingers of your right hand. There is no antidote to the deadly poison.", pageImage1: "", choices: 1, pageChoiceOneText: "The End", pageChoiceOneNav: 0, pageChoiceTwoText: "", pageChoiceTwoNav: 0, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

let p32 = Page(pageNumber: 32, dataEnteredBy: "Delgado", pageText: "With great sorrow, you decide that it is wisest to leave the expedition now. You can't risk returning to the great depths below. So, you reluctantly return to the United States. You are invited to tell of your adventures on several major television shows. While on one such show, a special news flash announces to the world the discovery of Atlantis. You regret your decision, but you didn't really have a choice. Did you?", pageImage1: "", choices: 1, pageChoiceOneText: "The End", pageChoiceOneNav: 0, pageChoiceTwoText: "", pageChoiceTwoNav: 0, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

let p33 = Page(pageNumber: 33, dataEnteredBy: "Delgado", pageText: "You can't resist the adventure beneath the sea. You must go down again, and after several weeks of rest, you enter the Seeker and slip quickly into the deep. You bring the Seeker to rest by the great canyon in the ocean bottom and, wearing your special suit, you venture out into the depths. There are no signs of the giant squid and you feel safe. Rounding a rock formation, you come upon the wreck of an ancient Greek ship. How strange to find this ship, intact, so far below the surface. What brought it here? Was it visiting Atlantis before the lost continent slipped beneath the sea? You take pictures and make notes in your special undersea book. Maybe this ancient ship hides the secret to Atlantis", pageImage1: "", choices: 2, pageChoiceOneText: "You go aboard the Greek ship.", pageChoiceOneNav: 45, pageChoiceTwoText: "You return to the surface to report your findings.", pageChoiceTwoNav: 46, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

let p34 = Page(pageNumber: 34, dataEnteredBy: "Delgado", pageText: "The dolphin looks at you, and you even imagine that he is smiling at you. You grab one of his flippers and with a powerfulswitch of his body, the dolphin swims upward. In a short time, you break through to the surface. You blink in the bright sun. The Maray is nowhere in sight. You are lost far at sea. The dolphin dives beneath the surface with you still clinging to him. He speeds off and within 20 minutes you are next to the Moray. The dolphin must have heard the Moray's engine noises underneath the water. Once aboard, everyone congratulates you on your escape. You will go down again, but the thought keeps haunting you: What if your luck has run out?", pageImage1: "", choices: 2, pageChoiceOneText: "You decide to dive again the next day.", pageChoiceOneNav: 48, pageChoiceTwoText: "You decide to give up the expedition.", pageChoiceTwoNav: 47, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

let p35 = Page(pageNumber: 35, dataEnteredBy: "Delgado", pageText: "You suddenly realize the stream of bubbles is powerful enough to raise the Seeker. You guide the Seeker into the bubble stream and it heads towards the surface. As you swirl upward, you begin to notice increasing amounts of brown kelp seaweed. Near the surface, you become entangled in the seaweed. The instruments in the Seeker indicate that the propellers and the steering mechanisms will not work. You put on your sea suit and go out to see what can be done. Once outside in the kelp, you realize that you can't free the Seeker. You start to swim for the surface but then you are soon completely stuck in the clinging seaweed. You are trapped and unable to go forward or return to the Seeker.", pageImage1: "", choices: 2, pageChoiceOneText: "You decide to keep struggling towards the surface.", pageChoiceOneNav: 50, pageChoiceTwoText: "You decide to rest quietly, gain strength, and work out a plan.", pageChoiceTwoNav: 53, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

let p36 = Page(pageNumber: 36, dataEnteredBy: "Delgado", pageText: "", pageImage1: "p36", choices: 1, pageChoiceOneText: "Continue", pageChoiceOneNav: 37, pageChoiceTwoText: "", pageChoiceTwoNav: 0, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

let p37 = Page(pageNumber: 37, dataEnteredBy: "Delgado", pageText: "The dolphin might help and might not. You decide to chance it alone. So, up you head, swimming towards the surface. The dolphin follows for some time, and then swims off. You rest for awhile about 300 feet below the surface before your final ascent. Then a large fish ugly, lumpy, puffed up, and covered with black and white markings swims towards you. Its bulging eyes fasten on you. It is a big-mouthed grouper, a fish which does not bother to bite its victims, butsimply swallowsthem whole. It looks as though you are its next meal.", pageImage1: "", choices: 1, pageChoiceOneText: "The End", pageChoiceOneNav: 0, pageChoiceTwoText: "", pageChoiceTwoNav: 0, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

let p38 = Page(pageNumber: 38, dataEnteredBy: "Delgado", pageText: "You decide to guide the Seeker into the new passageway to the bubble source. Suddenly the Seeker is swept downward as if pulled by a giant magnet. You lose consciousness. When you awake, you are in a well-lighted and comfortable room. Three people are standing close to you. They look normal and appear to be friendly. The middle one speaks. 'You are in the nether region of Atlantis. Thisis a visitors'reception room. If you wish to come into the city of Atlantis, then follow us; but you may never return to your world. If you wish to leave now, we will escort you safely to the surface. It is your choice. We do not wish to harm you.'", pageImage1: "", choices: 2, pageChoiceOneText: "You follow them into the city of Atlantis.", pageChoiceOneNav: 55, pageChoiceTwoText: "You decide to return to the surface.", pageChoiceTwoNav: 51, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

//Callan Kajdasz    39    46    Jacob Davis

// Checked by: Jacob
let p39 = Page(pageNumber: 39, dataEnteredBy: "Callan", pageText: "You are led to a room. The floors are a rich marble. The walls glow. The ceiling is like being inside a diamond looking through the many facets.A person who immediately commands respect beckons you with firmness and kindness to come to her.'Welcome to Atlantis. Thousands of years ago we learned that we were about to slip into the sea. Our people prepared for the calamity by building a new city inside an extinct volcano. We have lived here in peace and harmony ever since. We have no sunlight, nor stars to gaze at, but we have other spaces to meditate upon.' She tells you about a group of people called the Nodoors. If you wish, you can live with them, but you cannot leave Atlantis. A bearded man is to be your escort. Atlantis is a beautiful city. Buildings merge one into another, colors radiate light, and coral branches fill court yards. There is a sense of well-being and peace. It would be pleasant here, but you don't want to be a prisoner. Maybe there would be a better chance to escape if you join the Nodoors. You ask your guide about them. 'Oh, we believe they are dangerous, but we don't really know. They live in the center of the old volcano. If you wish, I can take you there.'", pageImage1: "",choices: 2, pageChoiceOneText: "You decide to join the Nodoors.", pageChoiceOneNav: 56, pageChoiceTwoText: "You decide to remain with the Atlanteans and perhaps get a chance to escape.", pageChoiceTwoNav: 57, pageChoiceThreeText: "", pageChoiceThreeNav: 0)



// Checked by: Jacob
let p40 = Page(pageNumber: 40, dataEnteredBy: "Callan", pageText: "The Atlanteans have lived in peace for thousands of years. They have no love of warfare. Their civilization is technologically very advanced and a sensing mechanism tells them that you are about to use your laser cannon. They quickly fire a special beam at the Seeker that makes all its functions stop. You are now powerless to escape. They walk up calmly to the Seeker and tell you to come with them to Atlantis. 'You are now part of Atlantis. We understand your fear, but do not be frightened. No harm will come to you and your life will be full. Follow us.' As you walk with them, into a new world, you wonder if you will ever see the sky again.", pageImage1: "",  choices: 1, pageChoiceOneText: "The End", pageChoiceOneNav: 3, pageChoiceTwoText: "", pageChoiceTwoNav: 0, pageChoiceThreeText: "", pageChoiceThreeNav: 0)
// Checked by: Jacob
let p41 = Page(pageNumber: 41, dataEnteredBy: "Callan", pageText: "You are greeted by a group of people who look like ordinary human beings except that there are gill-like slits on their necks. Their bare feet have skin between the toes forming a web. They order you to put on your sea suit, pull you quickly from the Seeker, and lead you towards their city. On the way they show you the zoo where there are ani mals from the world above the sea. There is a glass-like cage surrounding them filled with air, allowing them to live below the sea. The leader of the group explainsthat if you wish you may eithersubmit to an operation to have gills inserted so that you may breathe underwater, or you may join the other animals in the zoo.", pageImage1: "", choices: 2, pageChoiceOneText: "You agree to the operation.", pageChoiceOneNav: 58, pageChoiceTwoText: "You go to the zoo.", pageChoiceTwoNav: 59, pageChoiceThreeText: "", pageChoiceThreeNav: 0)
// Checked by: Jacob
let p42 = Page(pageNumber: 42, dataEnteredBy: "Callan", pageText: "Back aboard the Seeker, you radio the Maray that you are surfacing to make a plan. While rising out of the giant crevice-like canyon, you spot what appears to be a road running along the top of the ledge. What is this? The scientists aboard the Maray had mentioned the possibilities of finding signs of the ancient civilization, such asroads. You must investigate.", pageImage1: "", choices: 1, pageChoiceOneText: "Continue", pageChoiceOneNav: 6, pageChoiceTwoText: "", pageChoiceTwoNav: 0, pageChoiceThreeText: "", pageChoiceThreeNav: 0)
// Checked by: Jacob
let p43 = Page(pageNumber: 43, dataEnteredBy: "Callan", pageText: "You escape being seen by the submarine craft. Following the instructions you enter a passage way. At the end of the passageway is an airlock door and beyond it an incredibly large air-filled cavern. Perhaps it is the inside of an extinct volcano. The land is pleasant, although strange to your experience. A softsubstance covers the ground. It seems to be alive. You can't tell. A gentle light comes from the sides of this huge cavern. It re minds you of early morning light just before the sun rises. A group of people approach you with friendly gestures. They are wearing simple clothes much like the clothes people wore in ancient Greece. They are kind and generous. You remove your diving suit to find that the air is good to breathe. These people speak a language that is unknown to you, but one of them acts as an interpreter. You find out that this is Atlantis. They tell you it is governed by a man who is greedy, selfish, and dangerous. The people are like slaves. Everyone is unhappy except a few who serve the ruler as his lieutenants. These new friends ask for your help. Perhaps you can help them escape.", pageImage1: "", choices: 2, pageChoiceOneText: "you decide to leave your new friends and search for the ruler.", pageChoiceOneNav: 60, pageChoiceTwoText: "You decide to help your new friends escape.", pageChoiceTwoNav: 61, pageChoiceThreeText: "", pageChoiceThreeNav: 0)
// Checked by: Jacob
let p44 = Page(pageNumber: 44, dataEnteredBy: "Callan", pageText: "Quickly you get into the Seeker in an attempt to escape the strange submarine. You notice that the sub is chasing you so you put on full emergency ascent power. You could use your laser cannon to blast the sub, but you do not wish to hurt anyone. The ascent towardsthe surface isswift, but a few fathoms from the surface all systems on the Seeker fail. You are suspended in the water in a helpless position. It seems that a mysterious force has disabled you.", pageImage1: "", choices: 2, pageChoiceOneText: "You decide to wait on board the Seeker for help from the Maray.", pageChoiceOneNav: 64, pageChoiceTwoText: "You try to escape from the Seeker and try for the surface on your own.", pageChoiceTwoNav: 63, pageChoiceThreeText: "", pageChoiceThreeNav: 0)


// Checked by: Jacob
var p45 = Page(pageNumber: 45, dataEnteredBy: "Callan", pageText: "Cautiously you enter the ship's cabin. Clay jugs called amphorae, once filled with oils and wines, are strewn about. There are no remains of the crew. You do have a sense of being in ancient Greece and it is a strange feeling. A door leads to a smaller cabin. On a table near the rear of this cabin is a golden box. You open it and find the remains of a map. It does not show Atlantis. It shows that the ship was searching for a hole that leads to the center of the earth! You return to the Seeker and use the map to locate this incredible shaft to the center of the earth. Using some guesswork to interpret the map, you discover the tunnel opening, which appears to be roughly 100 feet in diameter. The sonar readings indicate the hole has no bottom.", pageImage1: "", choices: 2, pageChoiceOneText: "You decide to descend into the hole", pageChoiceOneNav: 65, pageChoiceTwoText: "You decide it is time to go back up to the surface", pageChoiceTwoNav: 66, pageChoiceThreeText: "", pageChoiceThreeNav: 0)
// Checked by: Jacob
var p46 = Page(pageNumber: 46, dataEnteredBy: "Callan", pageText: "The trip back to the surface is smooth, and finally the Seekeris hauled aboard the Maray. You climb out and are greeted by the scientists and crew. The Seeker is prepared for the second dive, but suddenly the wind rises and the sea kicks up into furious waves that crash over the deck of the Maray. All hands rush to prepare for hurricane force winds. There is no chance for the second dive to begin. All day and all night the Maray pitches on the stormy sea. The next morning the wind has died and the sky clear. You are now ready to dive again.", pageImage1: "", choices: 1, pageChoiceOneText: "Continue", pageChoiceOneNav: 48, pageChoiceTwoText: "", pageChoiceTwoNav: 0, pageChoiceThreeText: "", pageChoiceThreeNav: 0)


//Christian Kinz    47    54    Gabrel Delgado
var p47 = Page(pageNumber: 47, dataEnteredBy: "Christian Kinzie", pageText: "A helicopter is sent to pick you up and return you to an air base for a flight back to the United States. Newspaper reports indicate that the search for Atlantis has been given up. Several months later, however, a group of scientists get in touch with you because they believe that Atlantis can be found. They have put together another expedition and want you to join it. You are tempted. Adventure into the unknown is what you like.", pageImage1: "",choices: 1, pageChoiceOneText: "The End", pageChoiceOneNav: 0, pageChoiceTwoText: "", pageChoiceTwoNav: 0, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

var p48 = Page(pageNumber: 48, dataEnteredBy: "Christian Kinzie", pageText: "Again the Seeker is lowered over the side of the Maray and slipsinto the ocean. Fish swim by peering cautiously at you in your metal shell. The sunlight fades as you descend into the abyss. You are headed for the giant canyon below that might lead to Atlantis. When you reach the canyon you switch on the Seeker's searchlight. Immediately you spot the round hole that appears to be made by intelligent beings. Perhaps it leads to Atlantis.", pageImage1: "",  choices: 1, pageChoiceOneText: "Turn to page 9", pageChoiceOneNav: 9, pageChoiceTwoText: "", pageChoiceTwoNav: 0, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

var p49 = Page(pageNumber: 49, dataEnteredBy: "Christian Kinzie", pageText: "", pageImage1: "p49", choices: 1, pageChoiceOneText: "continue", pageChoiceOneNav: 50, pageChoiceTwoText: "", pageChoiceTwoNav: 0, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

var p50 = Page(pageNumber: 50, dataEnteredBy: "Christian Kinzie", pageText: "You are dizzy from lack of oxygen and fatigue. With your knife you slash away at the heavy brown kelp thatsurrounds you. Bit by bit, you seem to be getting free. Then suddenly you shoot up throughn the last clinging pieces of seaweed and reach the surface. You fire the special signal flare and the crew of the Maray quickly spot you. Within a few moments you are safely aboard, surrounded by your friends. What a relief to be out of that nightmare world!", pageImage1: "", choices: 2, pageChoiceOneText: "You dive again the next day.", pageChoiceOneNav: 67, pageChoiceTwoText: "You want to rest a few days and make emergency plans.", pageChoiceTwoNav: 68, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

var p51 = Page(pageNumber: 51, dataEnteredBy: "Christian Kinzie", pageText: "The three people of Atlantis sense your wish to return to the surface. Instantly, they produce a bubble-shaped capsule and put you inside. 'Farewell, earth person. May you live a long and prosperous life.' You shoot up swiftly through the sea and break out onto the surface near the Maray. The capsule that protected you disintegrates upon reaching the surface. Once aboard the Maray, you tell the crew and the scientists about your adventure. They are kind to you, but no one believes you. They think you have imagined the world of Atlantis as a result of being so deep for so long. Back in the United States, you begin a television tour telling about Atlantis. You write articles and a book. You are paid a great deal of money for this work. You are tempted to use this money for another expedition.", pageImage1: "", choices: 2, pageChoiceOneText: "You use your money for another expedition.", pageChoiceOneNav: 72, pageChoiceTwoText: "You decide to retire and lead a life of ease.", pageChoiceTwoNav: 74, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

var p52 = Page(pageNumber: 52, dataEnteredBy: "Christian Kinzie", pageText: "", pageImage1: "p52", choices: 1, pageChoiceOneText: "continue", pageChoiceOneNav: 53, pageChoiceTwoText: "", pageChoiceTwoNav: 0, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

var p53 = Page(pageNumber: 53, dataEnteredBy: "Christian Kinzie", pageText: "The worst thing you could do would be to panic. You relax and drift with the current which suddenly takes you upward. With your knife, you cut through the kelp and are free. What a relief. But no sooner do you get out of the kelp, than you are caught in the vortex of a giant whirlpool!", pageImage1: "", choices: 2, pageChoiceOneText: "You try to swim out of the whirlpool.", pageChoiceOneNav: 69, pageChoiceTwoText: "You dive into the vortex of the whirlpool hoping to reach the bottom and get out.", pageChoiceTwoNav: 70, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

var p54 = Page(pageNumber: 54, dataEnteredBy: "Christian Kinzie", pageText: "", pageImage1: "p54", choices: 1, pageChoiceOneText: "continue", pageChoiceOneNav: 55, pageChoiceTwoText: "", pageChoiceTwoNav: 0, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

//Cody Leavens      55    62    Emely Valadez-Bernal

let p55 = Page(pageNumber: 55, dataEnteredBy: "Cody", pageText: "The three people lead you into an enormous cavern. In the center of the cavern is a huge, silver-colored machine. It isshaped like a long tube with several round panels attached to one end. They lead you inside. It is the most advanced control room that you have everseen. Computers, sensing devices, recording devices, monitors, and a host of dials and panels fill the room. A strangely shaped figure with a very large head and totally blank eyes faces you. 'So, now you are in the control room of Atlantis. You see our secret. We landed on this planet 3000 years ago. We used our anti-matter device to sink this continent beneath the sea so we could escape from your people. You can have a most pleasant and useful life here with us if you wish. All you need to do is allow us to inject you with a special serum to enable you to live down here. It is up to you. On the other hand, if you do not wish to be one of us, you will be held prisoner.'", pageImage1: "", choices: 2, pageChoiceOneText: "You submit to the injection.", pageChoiceOneNav: 71, pageChoiceTwoText: "You decline.", pageChoiceTwoNav: 73, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

let p56 = Page(pageNumber: 56, dataEnteredBy: "Cody", pageText: "'I wish to join the Nodoors,' you tell your guide. He leads you to the outskirts of the city. 'I must leave you now. Good luck.' The Nodoors send a greeting party that is heavily armed. They are suspicious of you and believe that you are a spy sent by the Atlanteans. They look exactly like the Atlanteans, but they rarely smile. 'Come with us. You must be questioned. Perhaps you will work for us.' For 3 days you are questioned and kept in a small room without windows. These people are not kind and you believe that you have made a mistake. They ask you to help them spy on the Atlanteans. They suggest that, as a spy, you could pass freely between both groups.", pageImage1: "", choices: 2, pageChoiceOneText: "You decide to escape.", pageChoiceOneNav: 75, pageChoiceTwoText: "You decide to accept their offer.", pageChoiceTwoNav: 76, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

let p57 = Page(pageNumber: 57, dataEnteredBy: "Cody", pageText: "You decide to remain with the Atlanteans. Their approach to life seemsideal. Time isspent in creating things to help life and not to destroy it. You believe their leader is speaking the truth when she tells of avoiding war and of not hating. You are fascinated by this apparently ideal world. You would like to stay and search out the history of how Atlantis became what it is and what caused the split between the Atlanteans and the Nodoors. Yet, in your mind remains the hope of escape so that you can go back to your own world.", pageImage1: "", choices: 2, pageChoiceOneText: "You decide to stay and spend yourlife searching out the history and secrets of Atlantis.", pageChoiceOneNav: 77, pageChoiceTwoText: "You decide to escape.", pageChoiceTwoNav: 79, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

let p58 = Page(pageNumber: 58, dataEnteredBy: "Cody", pageText: "A large white lightshines down on you as you lie on the operating table. Then you become unconscious. Pleasant thoughts, sounds, and pictures occupy your mind. When you awake, you feel no pain nor any real change. But, now you can breathe underwater and join the Atlanteans in their world. For several weeks you explore the world under the sea as you never have seen it before. Without the heavy oxygen equipment on your back, you feel a marvelous sense of energy and you glide through a world of beauty. Your two guides have become very good friends and they take you on adventures in the deep, exploring the ocean bottom and getting to know the fish and other sea creatures. It is a very exciting life indeed. You like it, but you regret that you will never again know the world above the sea.", pageImage1: "", choices: 1, pageChoiceOneText: "The End", pageChoiceOneNav: 0, pageChoiceTwoText: "", pageChoiceTwoNav: 0, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

let p59 = Page(pageNumber: 59, dataEnteredBy: "Cody", pageText: "'No, I refuse to have this insane operation. I don't want to become a fish!' The Atlanteans try to convince you that life with them will be happy, useful, and long. Yet, you still refuse. Sadly they give up their arguments and spray you with a special mist that immediately knocks you out. Several hours later you gain your senses only to find that you are in an underwater air tank where you breathe naturally. Your closest neighbor is a horse who looks at you with sorrow and understanding. The Atlanteans have built a small apartment very much like the ones in the world above the sea. People come by and look at you and talk with you. Maybe you have made a real mistake. They no longer want you to join them in their world and way of life. You refused their offer and now you are a prisoner in a zoo.", pageImage1: "p59", choices: 1, pageChoiceOneText: "The End", pageChoiceOneNav: 0, pageChoiceTwoText: "", pageChoiceTwoNav: 0, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

let p60 = Page(pageNumber: 60, dataEnteredBy: "Cody", pageText: "It doesn't take you long to find the king. One of his countless agents leads you to him. He is in a small simple room with a strange light glowing from the rounded ceiling. 'So, you have found your way here after all. Put your mind at rest. I won't hurt you.' The king's booming voice startles you. He invites you to sit down. After several hours with the king, you find him to be bright, friendly, and interesting. Maybe the At- lanteans are wrong about this person. He offers you a chance to join his government. He tells you that most people are lazy and selfish and deserve to be ruled with power and com- mand. He has been king for almost 1000 years and he has survived because he is not afraid to be tough. He wants you to be an advisor on his staff.", pageImage1: "", choices: 2, pageChoiceOneText: "You decide to accept the king's offer and work for him.", pageChoiceOneNav: 80, pageChoiceTwoText: "You decide to refuse and go back to join the other people.", pageChoiceTwoNav: 82, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

let p61 = Page(pageNumber: 61, dataEnteredBy: "Cody", pageText: "The problem is where do they escape to? The king is in charge. He rules the world below the sea and his spies are everywhere. The only answer is to devise a plan to capture the king and put him in prison. The people are frightened. Some citizens tried to revolt years before and are still in prison. The king is smart and suspicious of everyone. You suggest a plan to put on a festival with a play. On a given signal the actors and the people in the audience will rise up and seize the king. The actors will be carrying real weapons, but no one will suspect them because they are in the play. The people like the plan. They ask you to be- come their leader.", pageImage1: "", choices: 2, pageChoiceOneText: "You accept their wish to become their leader.", pageChoiceOneNav: 81, pageChoiceTwoText: "You decide to help them in the planning, but also to escape from this sad world.", pageChoiceTwoNav: 86, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

let p62 = Page(pageNumber: 62, dataEnteredBy: "Cody", pageText: "", pageImage1: "p62", choices: 1, pageChoiceOneText: "Continue", pageChoiceOneNav: 63, pageChoiceTwoText: "", pageChoiceTwoNav: 0, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

//Shamsa Mohamed    63    70    Cole Perry
var p63 = Page(pageNumber: 63, dataEnteredBy: "shamsa", pageText: "There is one way out, you decide. Leave the Seeker and try to reach the surface on your own. You enter the airlock chamber which gives you access to the ocean. With a quick push off, you leave the Seeker and swim towards the surface. A small, yellow life raft is part of your escape equip- ment. The surface of the sea is calm, but the Maray is nowhere in sight. For 2 days and nights you drift in the life raft under hot sun and sharp starlight. At last a search helicopter spots you. Finally you are safe. The exploration of Atlantis will have to depend on a new diver. Your eyesight has been damaged by the strange force that immobilized the Seeker. You career as an underwater adventurer is over.", pageImage1: "", choices: 1, pageChoiceOneText: "The End", pageChoiceOneNav: 0, pageChoiceTwoText: "none", pageChoiceTwoNav: 0, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

var p64 = Page(pageNumber: 64, dataEnteredBy: "shamsa", pageText: "The best plan is to wait until the Maray locates you with sonar equipment. You can't signal the ship because none of the Seeker's electronic equipment is working. There is no sign of the mysterious submarine. Perhaps it has left, now that you have been chased away from the world of Atlantis. Looking out of the thick glass porthole, you see a giant blue whale heading for you. It looks as though the whale is going to ram you. Maybe the other submarine has angered the whale and it is seeking revenge on any craft near it. Suddenly the whale hits you full force. The Seeker is badly damaged. Water begins to trickle in through the hatch cover. You must abandon the Seeker. The whale now remains close to the Seeker watching and waiting.", pageImage1: "", choices: 3, pageChoiceOneText: "If you decide to try and escape.", pageChoiceOneNav: 63, pageChoiceTwoText: "If you try to hitch a ride on the whale.", pageChoiceTwoNav: 85, pageChoiceThreeText: "If you don't know what to do.", pageChoiceThreeNav: 87)

var p65 = Page(pageNumber: 65, dataEnteredBy: "shamsa", pageText: "Why not go? Who would believe it? The center of the earth! You push the control column forward and dive deep. Soon there is no more water, just a heavy gas that acts like water. You look at a world of colors and drifting forms. You pass by layers of rock and sand. Suddenly you sail into a gooey mass which almost fouls the Seeker's propellers. Then the Seeker's engine stops and you are pulled along through the semi-liquid material by some- thing like gravity or magnetism. You burst through a thick elastic membrane and enter an area of giant atoms. Electrons whirl around you at high speed, but there is plenty of room to maneuver between these fast-moving particles. The electrons are re- volving around a small mass you know is called the nucleus. You are able to avoid collisions with the electrons. What a world! Maybe you are having hallucinations.", pageImage1: "", choices: 2, pageChoiceOneText: "If you continue on in this trip to the center of the earth.", pageChoiceOneNav: 88, pageChoiceTwoText: "If you try to turn back.", pageChoiceTwoNav: 89, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

var p66 = Page(pageNumber: 67, dataEnteredBy: "Shamsa", pageText: "You face the fact that it is too dangerous to dive into a deep hole that might lead to the center of the earth. It is better judgment to return to the surface and work out a plan of action. You give one last look at the opening, check the Seeker's instruments and head up to the surface. Finally the Seeker breaks through into fresh air and sunlight and you wait to be picked up by the Maray.", pageImage1: "p67", choices: 1, pageChoiceOneText: "", pageChoiceOneNav: 32, pageChoiceTwoText: "", pageChoiceTwoNav: 0, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

var p67 = Page(pageNumber: 67, dataEnteredBy: "shamsa", pageText: "You insist that you are all right and will dive again the next day. The scientists try to convince you that it is foolhardy to go down again so soon. The captain of the Maray reportsthat a large storm system is coming and the next day will probably be the last day of diving for some time. Against advice, you enter the Seeker, wave farewell to all your friends and descend into the deep. You feel tired but excited. When you reach the bottom, you decide to explore the ledge along the deep canyon.", pageImage1: "", choices: 1, pageChoiceOneText: "", pageChoiceOneNav: 6, pageChoiceTwoText: "", pageChoiceTwoNav: 0, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

var p68 = Page(pageNumber: 68, dataEnteredBy: "shamsa", pageText: "A violent storm is reported heading your way. The captain decides to move the Maray to the shelter of a nearby island harbor. It is too danger- ous to remain where you are. Deckhands lash the Seeker securely to the deck of the Moray and you get underway. The storm breaks before you can reach the island harbor. The Seeker is torn loose and lost overboard. The monitors aboard the Maray are damaged by a frightful electric storm discharge. You are all alive but there are no funds to replace the damaged equipment. The expedition to Atlan- tis is over.", pageImage1: "", choices: 1, pageChoiceOneText: "The End", pageChoiceOneNav: 0, pageChoiceTwoText: "", pageChoiceTwoNav: 0, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

var p69 = Page(pageNumber: 69, dataEnteredBy: "shamsa", pageText: "It is no use. The whirlpool has you in its grip. You feel your arms and legs being torn in every direction. There is no way out. Round and round you go.", pageImage1: "", choices: 2, pageChoiceOneText: "If you use your laser pistol to blast a hole in the whirlpool wall", pageChoiceOneNav: 97, pageChoiceTwoText: "If you continue to struggle", pageChoiceTwoNav: 98, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

var p70 = Page(pageNumber: 70, dataEnteredBy: "shamsa", pageText: "You decide that you can't swim out of the whirlpool. There is only one thing to do. Dive deep into the center. You kick several times and hurl yourself into the center of the whirlpool. Lights and colors dance before your eyes. You lose all track of where you are. You find yourself standing on the ocean floor. You can look up through the center of the whirlpool and see the sky more than 2000 feet above you. It is a tiny patch of blue.", pageImage1: "", choices: 2, pageChoiceOneText: "If you try to return to the surface,", pageChoiceOneNav: 99, pageChoiceTwoText: "If you set out to explore this strange area,", pageChoiceTwoNav: 100, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

//Nathaniel Peoples 71    78    Cyrus Butcher

let p71 = Page(pageNumber: 71, dataEnteredBy: "Peoples", pageText: "Perhaps you are being foolish, but you decide to join them. The injection is painless and you feel no different than before. They lead you to a comfort- able room where you all share a special tea in celebration of your decision.', 'You see, all living beings are basically the same. Everything is connected in life. We have come from a different planet in search of other living beings. We have to be very careful about taking new people to our planet. Some of your people seek us out, just like you. We choose care- fully.', 'You are amazed at what they say. A choice is given to you. You can either journey with them through time and space to their planet, or you can remain in underwater Atlantis as a worker record- ing information about life on earth.", pageImage1: "", choices: 2, pageChoiceOneText: "You decide to travel with them in space and time", pageChoiceOneNav: 90, pageChoiceTwoText: "You decide to stay in Atlantis as a worker", pageChoiceTwoNav: 91, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

let p72 = Page(pageNumber: 72, dataEnteredBy: "Peoples", pageText: "The only way to prove that you are not crazy is to lead another expedition back to Atlantis. You take all the money from the TV appearances and articles and outfit a boat, hire a crew, rent the Seeker, and set sail. Most people think that you are out of your mind. You will show them. Poised over the spot you so carefully marked on the charts, you dive down in the Seeker. Again you find the hidden grotto and the round metal panel. The panel seems to seal off a passageway. It is locked. You try to open it with the Seeker's drilling arm, but it will not budge. It is frustrating to be so close to the secret and yet so far from it.", pageImage1: "", choices: 2, pageChoiceOneText: "Do you blast the panel with the laser beam?", pageChoiceOneNav: 93, pageChoiceTwoText: "You wait patiently to be observed and asked in", pageChoiceTwoNav: 94, pageChoiceThreeText: "", pageChoiceThreeNav: 0)
let p73 = Page(pageNumber: 73, dataEnteredBy: "Peoples", pageText: "The idea of being injected with a serum and joining them for the rest of your life is awful. You must plan an escape. When your captors are not looking, you slip away and dash for the door of the space craft. You fail to notice a laser beam guarding the exit hatch. Stepping into the laser beam, you freeze in mid- step. The Atlanteans gather round you sadly and tell you that you will have to remain this way for the earth equivalent of 23 years and 61 days until the effects wear off. Then you will be given a second chance.", pageImage1: "p73", choices: 1, pageChoiceOneText: "The End", pageChoiceOneNav: 0, pageChoiceTwoText: "", pageChoiceTwoNav: 0, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

let p74 = Page(pageNumber: 74, dataEnteredBy: "Peoples", pageText: "You argue with yourself for several weeks about setting out on a new expedition. Money is not the issue. You fear that finding Atlantis will ruin it for the Atlanteans. You believe that their civilization must be protected. You decide to use the money you have made to carry on research on space and life on planets in other galaxies. Someday perhaps you will meet the Atlanteans in space.", pageImage1: "", choices: 2, pageChoiceOneText: "You don't like this ending", pageChoiceOneNav: 107, pageChoiceTwoText: "The End", pageChoiceTwoNav: 0, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

let p75 = Page(pageNumber: 75, dataEnteredBy: "Peoples", pageText: "Escape will be difficult, but you decide that you must get away from these people. The best plan is to tell them that you want to accept their offer to spy on the Atlanteans. They are of course happy when you tell them that you will work for them. 'You see, the Atlanteans are jealous of us. We must be on our guard or else they will invade our area and capture us.' You don't believe the Atlanteans are at all jeal- ous of the Nodoors, but you won't argue. They take you back to the outskirts of their area, and you leave to join the Atlanteans. Once back with the Atlanteans, you ask them to allow you to live with them. You know that you will never be allowed to leave their underwater world, but there is always the hope for escape. It could be a good life.", pageImage1: "", choices: 1, pageChoiceOneText: "The End", pageChoiceOneNav: 0, pageChoiceTwoText: "", pageChoiceTwoNav: 0, pageChoiceThreeText: "", pageChoiceThreeNav: 0)
let p76 = Page(pageNumber: 76, dataEnteredBy: "Peoples", pageText: "'Ok, I'll do it,' you say. 'I'll join you and spy on the Atlanteans for you. Who knows, maybe they aren't as bad as you think.' The Nodoors are delighted that you will help them. They give you a room in a large building where most of them live. It is grey and forbidding, more like a prison than anything else. That night when all are asleep, you sit sleepless and realize that you are caught in a trap of your own making. It comes to you that the Nodoors are from a different planet and are unhappy outcasts. The Atlanteans want nothing to do with them. You chose the wrong side.", pageImage1: "", choices: 2, pageChoiceOneText: "You don't like this ending.", pageChoiceOneNav: 108, pageChoiceTwoText: "The End", pageChoiceTwoNav: 0, pageChoiceThreeText: "", pageChoiceThreeNav: 0)
let p77 = Page(pageNumber: 77, dataEnteredBy: "Peoples", pageText: "Maybe you can learn from the Atlanteans how they achieve such happiness in their lives. You will seek out their history. When you announce your decision to stay, you are treated with kindness and friendship. You ex- plain that you would like to help in their underwa- ter food production. Atlantis was an advanced civilization thousands of years ago. The citizens nourished their peaceful thoughts and plucked out their hateful thoughts as one would tend a garden. Their minds became a rich and dazzling universe, clear and unbounded. You have so much to do, helping with sea plants and studying their history that you soon forget the Seeker.", pageImage1: "", choices: 1, pageChoiceOneText: "The End", pageChoiceOneNav: 0, pageChoiceTwoText: "", pageChoiceTwoNav: 0, pageChoiceThreeText: "", pageChoiceThreeNav: 0)
let p78 = Page(pageNumber: 78, dataEnteredBy: "Peoples", pageText: "", pageImage1: "p78", choices: 1, pageChoiceOneText: "Continue", pageChoiceOneNav: 79, pageChoiceTwoText: "", pageChoiceTwoNav: 0, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

//Cole Perry        79    86    Dylan  Beasley
let p79 = Page(pageNumber: 79, dataEnteredBy: "Cole Perry", pageText: "When you get a chance and everyone is doing other things, you dash for the tunnel exit and makeit out into the water. No alarms sound. No one chases you. It is strange; they said they wouldn't allow you to return to the world above the sea. Why are they letting you escape? You swim toward the surface; then you black out. It is too deep. No one could survive the pressure and lack of oxygen. But a miracle has happened because you suddenly find yourself hacking away at brown seaweed that surrounds you and you are just a short way from the surface.", pageImage1: "",choices: 1, pageChoiceOneText: "Continue", pageChoiceOneNav: 50, pageChoiceTwoText: "", pageChoiceTwoNav: 0, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

// Checked by: ....
let p80 = Page(pageNumber: 80, dataEnteredBy: "Cole Perry", pageText: "An advisor to a king! What a chance. Maybe the king has ruled so long that he is out of touch with the people. Perhaps as his advisor you can help the people get what they want. You don't believe that people are lazy and selfish. The king just needs a new point of view. You are appointed the king's special advisor on problems of research on food and shelter. You immediately call general meetings of all the people to discuss the food program and the work schedules. The king is so glad to have someone else take over the problemsthat he leavesit in your hands entirely. He gives you land and a large salary. You set up new programs and schedules. The people are involved in the planning and the work. You listen to their complaints and their ideas. Life under the sea is rich and full. The people are hard working and good. It was a wise decision to remain.", pageImage1: "",  choices: 1, pageChoiceOneText: "THE END", pageChoiceOneNav: 0, pageChoiceTwoText: "", pageChoiceTwoNav: 0, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

let p81 = Page(pageNumber: 81, dataEnteredBy: "Cole Perry", pageText: "You do not wish to lead a revolt but the people need you. You organize the play, and the king is pleased to have his people involved in a project that keeps them busy and happy. The people can't wait for the day when they can put the king in prison and make their own decisions. The night of the play, the theater is filled, and everyone waits for the king to appear. But there is a delay. The crowd grows nervous. Then a messenger from the king runs into the theater and announcesthat the king has had a serious attack of brain fever. He may not live. You wonder whether the king is really ill or whether he has found out about the plot against him. The people are confused and do not know what to do. They turn to you and you tell them to go on with the play.Just then, a squad of the king's soldiers enter the theater. They are headed for you.", pageImage1: "", choices: 2, pageChoiceOneText: "You allow them to capture you.", pageChoiceOneNav: 116, pageChoiceTwoText: "You try to escape", pageChoiceTwoNav: 117, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

let p82 = Page(pageNumber: 82, dataEnteredBy: "Cole Perry", pageText: "Advisor to a mean king? Not a chance! You tell him that you want nothing to do with a tyrant who doesn't believe in people. You tell him to his face that the people are unhappy and angry. He laughs and tells you to go back to them if you wish. He warns you that the people are complainers, not workers. Once back with your new friends, you discuss how to overthrow the king and his henchmen. You hold secret meetings and work out a plan. But on the day of the overthrow, someone discovers a leak in the volcano wall of the underwater world. The entire civilization is in danger. All thoughts of revolt are forgotten. The Atlanteans must stop the sea from crashing in on them. Everyone works for a common purpose. Survival is the goal.", pageImage1: "", choices: 2, pageChoiceOneText: "You decide to work with them in this time of disaster", pageChoiceOneNav: 112, pageChoiceTwoText: "You decide to take advantage of this emergency to escape", pageChoiceTwoNav: 114, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

let p83 = Page(pageNumber: 83, dataEnteredBy: "Cole Perry", pageText: "", pageImage1: "p83", choices: 1, pageChoiceOneText: "Continue", pageChoiceOneNav: 84, pageChoiceTwoText: "", pageChoiceTwoNav: 9, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

let p84 = Page(pageNumber: 84, dataEnteredBy: "Cole Perry", pageText: "", pageImage1: "p84", choices: 1, pageChoiceOneText: "Continue", pageChoiceOneNav: 85, pageChoiceTwoText: "", pageChoiceTwoNav: 0, pageChoiceThreeText: "", pageChoiceThreeNav: 0)



var p85 = Page(pageNumber: 85, dataEnteredBy: "Cole Perry", pageText: "People ride dolphins, and you have met scuba divers who reported they held onto the flukes of whalesforshort rides. Itsounds crazy, but this may be your only way of escape. You leave the Seeker, swim to the whale, and grab its fluke. With a smooth powerful movement, the giant mammal begins to swim to the surface. You have trouble holding on. Then the whale breaksthe surface and lies there filling its lungs with air. You quietly swim away. You drift for 2 or 3 days, dozing and waking comfortably. You stay warm in your insulated sea suit and its special air packs keep you afloat. You are hungry and thirsty, but unharmed by the time the search helicopter spots you bobbing in the waves.", pageImage1: "", choices: 1, pageChoiceOneText: "THE END", pageChoiceOneNav: 0, pageChoiceTwoText: "", pageChoiceTwoNav: 63, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

var p86 = Page(pageNumber: 86, dataEnteredBy: "Cole Perry", pageText: "It is their world, but you are willing to help them with the planning for the overthrow of the king. You want no real part in the revolt. The planning requires choosing new leaders and setting goals for the people. You almost decide to join them in the actual revolt, but you really want to get back to your own world. Once the revolt is underway, you hope to slip away and return to the Seeker for a quick escape to the surface of the ocean. The day of the revolt, you can't resist the excitement of the Atlanteans'bold enterprise, and you decide to stay with them and help in any way that you can. The endless planning and training pays off. The carefully selected band of men and women easily capture the king and his guards. The revolt has succeeded without shedding a drop of blood and the people celebrate for days. The Atlanteans treat you as if you are one of them, and, for the first time, you feel that you are.", pageImage1: "", choices: 1, pageChoiceOneText: "THE END", pageChoiceOneNav: 0, pageChoiceTwoText: "", pageChoiceTwoNav: 0, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

//Aeneas Reynolds   87    94    Cody Leavens
var p87 = Page(pageNumber: 87, dataEnteredBy: "Reynolds", pageText: "You admit that you just don't know what to do.The whale is frightening looking and you don't have any escape plans. So you wait and watch and listen. After what seems a long time, but is probably just a few minutes, the mysterious submarine re-turns, attaches a cable to the Seeker, and pulls you up to the surface. Then the submarine vanishes under the wavesleaving you to wait for the Maray.", pageImage1: "p87", choices: 1, pageChoiceOneText: "The End", pageChoiceOneNav: 0, pageChoiceTwoText: "", pageChoiceTwoNav: 0, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

var p88 = Page(pageNumber: 88, dataEnteredBy: "Reynolds", pageText: "The electrons whirl about at dizzy speeds and you continue until you get to a spot where your instruments indicate that there is no time. The clocks stop, the speed indicator stops, your heart stops, and yet you are alive. Every sense in your body seems more alive than ever before. You hear beautiful music and see lights that you feel and taste as well. Peace and well-being fill you. You become aware of other beings close to you. No one has entered through the only hatch and yet there are other presences in the Seeker. Turning around, you see three Atlanteans. Then you feel that the Seeker has become just a thought and that the people from Atlantis have entered your mind and are aboard the Seeker. You try to enter their thoughts, but they tell you that you have not journeyed far enough yet to be able to become a thought-traveler.", pageImage1: "", choices: 2, pageChoiceOneText: "If you try to turn back from this strange world, turn to page 95", pageChoiceOneNav: 95, pageChoiceTwoText: "If you decide to travel in throught-time-space, turn to page 96", pageChoiceTwoNav: 96, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

var p89 = Page(pageNumber: 89, dataEnteredBy: "Reynolds", pageText: "No, you will not dive down toward the center of the earth. Once through the thin outer layer of the earth, you know that the regions beneath change from solid to molten and then to a hard core. At least that is the theory given by the scientists. You couldn't possibly survive such a journey. Anyway, you think that your sonar gear is probably not working correctly. The hole is deep, but you don't believe that it really goes all the way to the center of the earth. Caution is your approach. You go back to the surface to consult with the scientists aboard the Moray. The scientiststell you that their instruments have been damaged, perhaps by an approaching storm, and they too, are cautious. They decide to move the Maray away from the site of the mysterious hole. The expedition retreats and you know your chance to discover Atlantis has slipped away.", pageImage1: "", choices: 1, pageChoiceOneText: "The End", pageChoiceOneNav: 0, pageChoiceTwoText: "", pageChoiceTwoNav: 0, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

var p90 = Page(pageNumber: 90, dataEnteredBy: "Reynolds", pageText: "'I will go with you. I want to see other parts of the universe." "Congratulations. You will not regret this. We are ready to depart.' They take you to a small room and three of them stand with you under a beam of intense light. You feel a rush of speed, and yet you are not moving. You feel as though you have traveled hundreds of thousands of milesin space. You rush past the sun, past and through the Milky Way, and on into other galaxies. Yet, you feel asthough you are stillstand- ing in the same spot. Then you are on the planet Aygr where the Atlanteans came from. It is a world of fantastic shapes and strange plants. The city gleams like a thousand search lights. The shapes that must be their buildings are pure light pulsing with energy. Nothing is hard or sharp. Everything is light. You see no people, just forms of brighter light that move. Suddenly, some of the moving forms change into Atlanteans. 'Our bodies are not important. It is our energy that isimportant. You can see usin our body forms if you wish, but we only use them to communicate with people like you. You may choose to remain as you are or accept transformation.'", pageImage1: "", choices: 2, pageChoiceOneText: "If you decide to stay in your body form, turn to page 101.", pageChoiceOneNav: 101, pageChoiceTwoText: "If you decide to be transformed into an energy shape, turn to page 102", pageChoiceTwoNav: 102, pageChoiceThreeText: "", pageChoiceThreeNav: "")

var p91 = Page(pageNumber: 91, dataEnteredBy: "Reynolds", pageText: "You have had enough adventure for now. Travel to another planet in a different galaxy sounds like more risk than you wish to take. Be- sides, you can always go later. You tell the people that you wish to stay and work in their society. Perhaps your knowledge of the sea can help them. They discuss your case very seriously for several days. When they are through talking, they offer you a choice of jobs in Atlantis. You may become a farmer or a musician.", pageImage1: "", choices: 2, pageChoiceOneText: "If you decide to become an underwater farmer, turn to page 103", pageChoiceOneNav: 103, pageChoiceTwoText: "If you decide to become a musician, turn to page 104", pageChoiceTwoNav: 104, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

var p92 = Page(pageNumber: 92, dataEnteredBy: "Reynolds", pageText: "", pageImage1: "p92", choices: 0, pageChoiceOneText: "", pageChoiceOneNav: 0, pageChoiceTwoText: "", pageChoiceTwoNav: 0, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

var p93 = Page(pageNumber: 93, dataEnteredBy: "Reynolds", pageText: "You'll try to blast the hatch right off its hinges. You have the power. Your finger presses the red button that fires the laser cannon. A blinding flash erupts immediately. But the hatch remains firm. You fire again and again and again. Each time the Seeker is rocked by the force of the laser cannon. The reflected energy is damaging to your craft. You continue to fire the cannon, holding your finger on the button. Then there is a blinding flash inside the Seeker itself. The laser cannon has exploded. You and the Seeker are destroyed instantly. The hatch remains closed.", pageImage1: "", choices: 1, pageChoiceOneText: "The End", pageChoiceOneNav: 0, pageChoiceTwoText: "", pageChoiceTwoNav: 0, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

var p94 = Page(pageNumber: 94, dataEnteredBy: "Reynolds", pageText: "It is never good to use force unless you are attacked and must defend yourself. You refuse even to consider using the laser cannon; it might kill people and would certainly destroy any chance for friendship. You decide to wait patiently and hope that you will be noticed and invited in. For six hours you sit quietly and wait for some sign. A green glow comes from the area ahead of you. It bathes the Seeker in a gentle light. The hatch door opens. Three figures emerge and beckon to you to follow them.", pageImage1: "", choices: 2, pageChoiceOneText: "If you follow, turn to page 105", pageChoiceOneNav: 105, pageChoiceTwoText: "If you refuse to follow them, turn to page 106", pageChoiceTwoNav: 106, pageChoiceThreeText: "", pageChoiceThreeNav: 0)


//Johnny Slabaugh   95    102   Christian Kinzie
let p95 = Page(pageNumber: 95, dataEnteredBy: "Johnny Slabaugh", pageText: "This is too much for you. It is like a nightmare and you decide to turn back. But going back is much harder than you expected. The electrons whirl closer and closer to you as though they were guards keeping you from leaving. It is difficult to guide the Seeker in this maze of atoms. The in-struments are useless now. The figures of the At-lanteans disappear. Suddenly, you are caught in the elastic membrane that almost stopped you before. It sticks to the Seeker, holding you back. You want to be free and return to the world you have known all your life. You lose consciousness and wake up several hours later in your sea suit floating above the hole in the ocean floor. The Seeker is gone. You're dazed: did you dream the whole thing? Slowly you return to the surface, but the Maray has disap- peared. You can't decide how much time haselapsed. You realize that your crew must think you are lost forever and you know they are right. The waves rock your unresisting body back and forth as you float alone in the vast sea. You feel your strength slowly draining away.", pageImage1: "", choices: 1, pageChoiceOneText: "The End", pageChoiceOneNav: 0, pageChoiceTwoText: "", pageChoiceTwoNav: 0, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

let p96 = Page(pageNumber: 96, dataEnteredBy: "Johnny Slabaugh", pageText: "A thought traveler! You realize that people do it all the time in day dreams. Of course, you want to be a thought traveler, but how? The Atlanteans speak softly and tell you that all things are the same— past, present, future are all the same. It simply requires you to concentrate and put your thoughts where you wish them to be. You try, and amazingly you are rapidly rushed through time to the day you were born, then to the day you made your first deep-sea dive. Your mind flies from one time in your life to another. But when it comesto the future, you meet a blank wall. You can't seem to travel into the future. 'Why can't I travel ahead in time,' you ask the Atlanteans. 'Be patient,' they reply. 'All in good time.' Suddenly you whirl through time into the outer reaches of the universe where you can actually feel the light going through you. You cast no shadow. A sense of peace fills you.", pageImage1: "", choices: 2, pageChoiceOneText: "You decide to drop out of thought travel and return to earth life.", pageChoiceOneNav: 110, pageChoiceTwoText: "The End.", pageChoiceTwoNav: 0, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

let p97 = Page(pageNumber: 97, dataEnteredBy: "Johnny Slabaugh", pageText: "You have a laser pistol that you carry for emergencies. You blast a hole in the whirlpool wall and dive through it. Facing you is a school of fish who are puzzled by this strange intruder. Behind them lurks the form of a shark. You swim toward the surface slowly and the shark vanishes into the deep. The Maray is nowhere in sight. You are wonder- ing how long you'll be waiting when a loud splash- ing sighing sound startles you. A huge whale has surfaced and lies nearby spouting and sucking in great noisy draughts of air. It take you a good half hour to swim to the enormous creature. It pays no attention to you. You climb onto its tail and crawl on hands and knees toward the highest point of its back. It's like creeping up a gigantic grey rock. From your vantage point on top, sure enough, you can see the Moray and the tiny glint of binocu- lar lenses reflecting in the sun. The Maray crew is watching the whale. You wave, feeling certain they have seen you. It won't be long before they come to collect you.", pageImage1: "p97", choices: 1, pageChoiceOneText: "The End", pageChoiceOneNav: 0, pageChoiceTwoText: "", pageChoiceTwoNav: 0, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

let p98 = Page(pageNumber: 98, dataEnteredBy: "Johnny Slabaugh", pageText: "You faint, and when you come to, you are floating on the surface of the ocean. There is a heavy ocean swell and the sun beats down on you. The whirlpool must have stopped as quickly and mysteriously as it began. You feel dizzy and exhausted and you move gently to make sure you haven't broken any bones. As you move your head slowly inside your helmet, you feel an intense pain shooting across your right temple. You have to lie very still then and gradually your ears pick up the thrum of the search helicopter. You don't dare move to look, but as the minutes go by, the thrum gets louder and slowly disappears. The helicopter has passed over you. It won't return this way. The pain in your temple increases. You begin to lose consciousness.", pageImage1: "", choices: 1, pageChoiceOneText: "The End", pageChoiceOneNav: 0, pageChoiceTwoText: "", pageChoiceTwoNav: 0, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

let p99 = Page(pageNumber: 99, dataEnteredBy: "Johnny Slabaugh", pageText: "The walls of the whirlpool look like solid ridges sloping upwards to the surface. The water is rush- ing so fast that the center looks absolutely calm. You wonder if perhaps you could swim up through that calm. It's worth a try, and you set off. Before you can tell if you're making any progress, the whirlpool reverses and instead of whirling down, it whirls up and catapults you out of the ocean and into the air. You fall back onto the surface of the ocean close to the Maray. Although you are stunned by the fall, you quickly gain your senses and are picked up by the ship. Of course no one believes your story, but then even you think it is almost too fantastic to have happened.", pageImage1: "", choices: 1, pageChoiceOneText: "The End", pageChoiceOneNav: 0, pageChoiceTwoText: "", pageChoiceTwoNav: 0, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

let p100 = Page(pageNumber: 100, dataEnteredBy: "Johnny Slabaugh", pageText: "The ocean floor has a small metal hatch on it. You pull with all your strength but it will not open. You rest for a moment and look through the wall of watersurrounding you. Two fish stare back at you! It's asthough you are in an aquarium for the fish to look at. You don't hear the hatch open. A voice com- mands you to enter. With fear and caution you walk down a corridor that leads to a small room. Three people meet you.", pageImage1: "", choices: 1, pageChoiceOneText: "Turn to page 55", pageChoiceOneNav: 55, pageChoiceTwoText: "", pageChoiceTwoNav: 0, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

let p101 = Page(pageNumber: 101, dataEnteredBy: "Johnny Slabaugh", pageText: "You just can't give up your body. It might be all right for the Atlanteans to move about as pure energy, but you have not reached a point where you are willing to risk what you are for what they are. It isstrange wandering about with bright glowing blobs of energy moving with you. They ask you to give talks about life on earth as you know it, and you agree. For two years you meet with the Atlan- teans in their energy forms and talk about earth and how people live and what they do. The Atlan- teans are interested in all aspects of earth life: the technology, politics, wars, and religion. You ask them why, but they never give you a direct answer. Then one day you look down at yourself and you only see bright, glowing energy. With horror you realize you have become one of them.", pageImage1: "", choices: 1, pageChoiceOneText: "The End", pageChoiceOneNav: 0, pageChoiceTwoText: "", pageChoiceTwoNav: 0, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

let p102 = Page(pageNumber: 102, dataEnteredBy: "Johnny Slabaugh", pageText: "You are in the Atlantean world; why not be- come like an Atlantean? Looking down at your hands, you see them gradually begin to glow with a warm, yellow light. Little by little, the glow travels up your arms and legs until suddenly you have no body left. You are a glowing energy form. You feel a sense of freedom and happiness that you have never known before. You can float, or fly, or zoom anywhere you want to. No wallsstop you; you just melt through them. You don't need food or rest. You can travel through time, and you can travel instantly back to earth in your energy form. You feel that this is the way you want to be.", pageImage1: "p102", choices: 1, pageChoiceOneText: "The End", pageChoiceOneNav: 0, pageChoiceTwoText: "", pageChoiceTwoNav: 0, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

//Max Stephenson    103   110   Callan Kajdasz

var p103 = Page(pageNumber: 103, dataEnteredBy: "Max", pageText: "Farming under the sea is a job that you enjoy. Outside Atlantis, there are fields of sea plants that are worked on just like gardens above the sea. Atlanteans go out each day and harvest the plants, take care of the fields, and chase away the fish that love to nibble on the growing plants. Then there are fish pens to work on. There you feed and tend the fish until they are needed for food. Farming under the sea is beautiful and it is much easier than you had imagined. Danger lurks, though, in the form of sting rays, slender sea snakes, and occa- sional sharks. You have to be on your guard at all times. The End", pageImage1: "", choices: 1, pageChoiceOneText: "End", pageChoiceOneNav: 0, pageChoiceTwoText: "", pageChoiceTwoNav: 0, pageChoiceThreeText: "", pageChoiceThreeNav: 0)
// Checked by: Callan
var p104 = Page(pageNumber: 104, dataEnteredBy: "Max", pageText: "A musician in the world of Atlantis. Who would believe it? You are asked to choose an instrument to play. You examine water lutes, sea drums, shark bone flutes, and a wide range of electronic instru- ments. You choose one of the electronic instru- ments, but it makes no sound at all. You are told that it plays music that people feel rather than hear. What a world you're living in! Who would believe in music that is not heard? Gradually you learn to feel the different notes with parts of your body: your thighs, chest, temples, and fingertips. Your interest in this new way of sensing music grows with each day. You master this new art form. You become their greatest musician. The End", pageImage1: "", choices: 1, pageChoiceOneText: "End", pageChoiceOneNav: 0, pageChoiceTwoText: "", pageChoiceTwoNav: 0, pageChoiceThreeText: "", pageChoiceThreeNav: 0)
// Checked by: Callan
var p105 = Page(pageNumber: 105, dataEnteredBy: "Max", pageText: "These people lead you to a control room. There you meet the commander of an underwater scien- tific center that is conducting secret research into life underneath the sea. They inform you that it was a good thing that you did not use your laser cannon, because they have anti-laser devices that would have blown you and the Seeker to pieces.After a pleasant meal and a tour of the deep- water lab, you are sent back to the Seeker for a return journey to the surface. You are told never to return again; if you do, you will be kept a prisoner for the rest of your life.The End", pageImage1: "p105", choices: 1, pageChoiceOneText: "End", pageChoiceOneNav: 0, pageChoiceTwoText: "", pageChoiceTwoNav: 0, pageChoiceThreeText: "", pageChoiceThreeNav: 0)
// Checked by: Callan
var p106 = Page(pageNumber: 106, dataEnteredBy: "Max", pageText: "When you refuse to follow them, they take out small hand-held hypnotizers that put you into a deep trance. You are led through a long tunnel into a large underwater lab. Three military techni- cians come up to you and break the trance.'You have stumbled into a secret military base. We're developing too many secret plans to risk being discovered. You will remain our prisoner.' There is no escape.The End", pageImage1: "p106", choices: 1, pageChoiceOneText: "End", pageChoiceOneNav: 0, pageChoiceTwoText: "", pageChoiceTwoNav: 0, pageChoiceThreeText: "", pageChoiceThreeNav: 0)
// Checked by: Callan
var p107 = Page(pageNumber: 107, dataEnteredBy: "Max", pageText: "You argue with yourself for weeks. Then you decide to go back to Atlantis. You are in such a hurry to return that you hire a small, fast hydrofoil craft to take you to the spot in the ocean where Atlantis is. Once reaching the spot, you intend to make a dive with just scuba gear! You know a 2000 foot dive is impossible. But you don't care; you feel you must make the attempt.A storm rips the sea for six days and when it clears you prepare to dive. Just as you slip into the water, you look up into the sky and high above the clouds you see the sparkling city of Atlantis. No dive is necessary.The End", pageImage1: "", choices: 1, pageChoiceOneText: "End", pageChoiceOneNav: 0, pageChoiceTwoText: "", pageChoiceTwoNav: 0, pageChoiceThreeText: "", pageChoiceThreeNav: 0)
// Checked by: Callan
var p108 = Page(pageNumber: 108, dataEnteredBy: "Max", pageText: "During the night, you are awakened by the sound of voices talking quietly. Listening, you realize that a group of Nodoors is planning an escape. They want to join the Atlanteans. They believe that life in Atlantis can be better for them. You join them and listen to the stories of fear and darkness. They seek light and friendship. It sounds simple, but nothing is easy.", pageImage1: "p108", choices: 1, pageChoiceOneText: "Continue", pageChoiceOneNav: 109, pageChoiceTwoText: "", pageChoiceTwoNav: 0, pageChoiceThreeText: "", pageChoiceThreeNav: 0)
// Checked by: Callan
var p109 = Page(pageNumber: 109, dataEnteredBy: "Max", pageText: "Suddenly the door bursts open. Three guards armed with special weapons rush in. They fire the weapons and in a flash of brilliant light you and your companions are vaporized.The End", pageImage1: "p109", choices: 1, pageChoiceOneText: "End", pageChoiceOneNav: 0, pageChoiceTwoText: "", pageChoiceTwoNav: 0, pageChoiceThreeText: "", pageChoiceThreeNav: 0)
// Checked by: Callan
var p110 = Page(pageNumber: 110, dataEnteredBy: "Max", pageText: "Over 1000 years of thought travel later, you are called into the main thinking room. You are told that you may now return to earth life. You have doubts about going back, but you are curious to see what changes have occurred while you were living in Atlantis.What a sight greets you as you circle earth at an altitude of 1000 feet! The great cities of the world, New York, London, Paris, and Hong Kong are overgrown with vegetation. The roads leading into the cities are barely visible. But you see signs of new settlements. There are clusters of buildings spread out in the countryside. You don't see any smokestacks. There are few roads and no cars. The people live a simple life providing themselves with food, shelter, and clothing. You wish to join them.The End", pageImage1: "p110", choices: 1, pageChoiceOneText: "End", pageChoiceOneNav: 0, pageChoiceTwoText: "", pageChoiceTwoNav: 0, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

//Emely Valadez     111   117   Aeneas Reynolds

var p111 = Page(pageNumber: 111, dataEnteredBy: "Emely", pageText: "One day your friendstell you that you can return to earth if you wish. You consider it carefully and decide that because of your thought traveling ability, the life you now lead is what you want. You decide to stay where you are forever.", pageImage1: "", choices: 1, pageChoiceOneText: "The End", pageChoiceOneNav: 0, pageChoiceTwoText: "", pageChoiceTwoNav: 0, pageChoiceThreeText: "", pageChoiceThreeNav: 0)
var p112 = Page(pageNumber: 112, dataEnteredBy: "Emely", pageText: "Years ago the Atlanteans had worked outemergency procedures, but most people had forgotten them. One old person remembers where the emergency instructions and equipment were kept. You and the Atlanteans work without stop for 72 hours pumping out the flooding waters and building a special retaining wall around the volcanic crack. Finally the last pump is shut off. You are all exhausted, but you've won in your battle against the sea.", pageImage1: "p44", choices: 1, pageChoiceOneText: "The End", pageChoiceOneNav: 0, pageChoiceTwoText: "", pageChoiceTwoNav: 0, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

var p113 = Page(pageNumber: 113, dataEnteredBy: "Emely", pageText: "", pageImage1: "p113", choices: 0, pageChoiceOneText: "", pageChoiceOneNav: 0, pageChoiceTwoText: "", pageChoiceTwoNav: 0, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

var p114 = Page(pageNumber: 114, dataEnteredBy: "Emely", pageText: "With everyone worried about the sea crashing in, no one will notice you if you try to escape. You run down a long, little-used corridor that leads to the sea. The exit door is heavy and rusty from not being used. You push with all your might, and finally it swings open into an airlock to the open water. You push the emergency release button and shoot out into the water. The Seeker is where you left it, and once inside, you head for the surface where the Maray waits for you.", pageImage1: "", choices: 1, pageChoiceOneText: "The End", pageChoiceOneNav: 0, pageChoiceTwoText: "", pageChoiceTwoNav: 0, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

var p115 = Page(pageNumber: 115, dataEnteredBy: "Emely", pageText: "", pageImage1: "p115", choices: 0, pageChoiceOneText: "", pageChoiceOneNav: 0, pageChoiceTwoText: "", pageChoiceTwoNav: 0, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

var p116 = Page(pageNumber: 116, dataEnteredBy: "Emely", pageText: "It is uselessto try to escape the soldiers. You are surrounded. They take you to the king, and he sadly tells you that you are just like all the rest. He can't trust anyone. He will have to decide what to do with you and in the meantime he throws you into the dungeon.", pageImage1: "p116", choices: 1, pageChoiceOneText: "The End", pageChoiceOneNav: 0, pageChoiceTwoText: "", pageChoiceTwoNav: 0, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

var p117 = Page(pageNumber: 117, dataEnteredBy: "Emely", pageText: "How can you escape? The soldiers are coming after you. You yell as loud as you can and everyone in the theatersurrounds you, forming a barrier to the soldiers. The soldiers stare at the people all around them, hesitate, and then quickly leave. They know that the odds are too great to win such a fight. The people cry for the revolt to go on. The crowd leaves the theater and heads to the king's quarters. All along the route people join you and even the king's soldiers begin to join the crowd. You and the people are free; the king is put inprison. The revolt is a success.", pageImage1: "", choices: 1, pageChoiceOneText: "The End", pageChoiceOneNav: 0, pageChoiceTwoText: "", pageChoiceTwoNav: 0, pageChoiceThreeText: "", pageChoiceThreeNav: 0)

